note hide: user.chicken_notes_hide()
note show: user.chicken_notes_show()
note expand: user.chicken_notes_expand()
note collapse: user.chicken_notes_collapse()
note move: user.chicken_notes_move_display()
note page <number>: user.chicken_notes_go_to_page(number)
note page next: user.chicken_notes_go_to_next_page()
note page (last|previous): user.chicken_notes_go_to_previous_page()
note copy link <number>: user.chicken_notes_copy_link(number)
note open link <number>: user.chicken_notes_open_link(number)