note hide: user.chicken_notes_hide()
note show: user.chicken_notes_show()
note expand: user.chicken_notes_expand()
note collapse: user.chicken_notes_collapse()
note move: user.chicken_notes_move_display()